// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWmc4pym2qu8mfclHXXTBYLg4wyssUVcI',
    appId: '1:560204759453:web:0bc51d71a1e7b4221daf74',
    messagingSenderId: '560204759453',
    projectId: 'baking-e6b81',
    authDomain: 'baking-e6b81.firebaseapp.com',
    storageBucket: 'baking-e6b81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAsc-sr7XhHcQ0UIZK1xhCsEdUnUVnn0',
    appId: '1:560204759453:android:fa81c66b73c5aefa1daf74',
    messagingSenderId: '560204759453',
    projectId: 'baking-e6b81',
    storageBucket: 'baking-e6b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABcBORPE5aKL8TndMX2g74dhogBOhtBTM',
    appId: '1:560204759453:ios:d4cbb48fff2995c91daf74',
    messagingSenderId: '560204759453',
    projectId: 'baking-e6b81',
    storageBucket: 'baking-e6b81.firebasestorage.app',
    androidClientId: '560204759453-lrq80eooitbsfqbtn2isou1ir9o9ra1r.apps.googleusercontent.com',
    iosClientId: '560204759453-80vgmera2l7irs4p5oboug17m42l3fe4.apps.googleusercontent.com',
    iosBundleId: 'com.example.a1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABcBORPE5aKL8TndMX2g74dhogBOhtBTM',
    appId: '1:560204759453:ios:d4cbb48fff2995c91daf74',
    messagingSenderId: '560204759453',
    projectId: 'baking-e6b81',
    storageBucket: 'baking-e6b81.firebasestorage.app',
    androidClientId: '560204759453-lrq80eooitbsfqbtn2isou1ir9o9ra1r.apps.googleusercontent.com',
    iosClientId: '560204759453-80vgmera2l7irs4p5oboug17m42l3fe4.apps.googleusercontent.com',
    iosBundleId: 'com.example.a1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWmc4pym2qu8mfclHXXTBYLg4wyssUVcI',
    appId: '1:560204759453:web:2ec119a8ee0046da1daf74',
    messagingSenderId: '560204759453',
    projectId: 'baking-e6b81',
    authDomain: 'baking-e6b81.firebaseapp.com',
    storageBucket: 'baking-e6b81.firebasestorage.app',
  );

}